- name: Install packages
  ansible.builtin.include_tasks: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts['distribution'] | lower }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] | lower }}.yml"
        - default.yml

- name: Start qemu-agent
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
